[build]
  command = "npm run build"

[build.environment]
  NEXT_DISABLE_ESLINT = "1"
  NEXT_DISABLE_TYPECHECK = "1"
  NEXT_TELEMETRY_DISABLED = "1"

[build.cache]
  paths = [
    "node_modules/**",
    ".next/cache/**"
  ]

